import sys

def help():
    if len(sys.argv) == 2:
        print()
        print("JETS Command Line Tool Made by Jonathan Thorne")
        print("Commands: ")
        print()
        print("      -l                    Prints all articles in all volumes")
        print("      -l (1-62)             Prints all articles in given volume")
        print("      -l (1-62).(1-4)       Prints all articles in given volume and issue")
        print()
        print("      -s -t searchterm(s)   Searches for that term in all article titles")
        print("      -s -a authorname      Searches for that author and displays all their articles*")
        print()
        print("  * Note that last names work best with author searches")
        print()
        print("      -f (1-62)             Fixes the author info on all articles in given volume")
        print("      -f (1-62).(1-4)       Fixes the author info on all articles in given issue")
        print()
        print("      -fr (1-62).(1-4).##   Where ## is the article number, allows user to rename the file manually")
        print()
        print("      -c (1-62).(1-4).##    Where ## is the article number, displays the author on given article")
        print()
        print("      -fo                   Fixes output files to a permanent name")
        print()
        print("      -ca                   Moves all articles to correct author folder")
        print("      -ca (1-64)            Moves all articles in given volume to correct author folder")
        print("      -ca (1-64).(1-4)      Moves all articles in given issue to correct author folder")
        print("      -ca (1-64).(1-4).##   Moves given article to correct author folder")
        print()
        print("      -o (1-64).(1-4).##    Where ## is the article number, opens the article")
        print()
    elif len(sys.argv) == 3:
        arg = sys.argv[2]
        if arg == "-l":
            print()
            print("List Command")
            print()
            print("Description: Lists all articles, or all articles in a volume or issue")
            print()
            print("Usage:")
            print("      -l                    Prints all articles in all volumes")
            print("      -l (1-62)             Prints all articles in given volume")
            print("      -l (1-62).(1-4)       Prints all articles in given volume and issue")
        elif arg == "-s":
            print()
            print("Search Command")
            print()
            print("Description: Search by title or author")
            print()
            print("Usage:")
            print("      -s -t searchterm(s)   Searches for that term in all article titles")
            print("      -s -a authorname      Searches for that author and displays all their articles*")
            print()
            print("  * Note that last names work best with author searches")
        elif arg == "-f":
            print()
            print("Fix Author Command")
            print()
            print("Description: Goes through a set volume or issue and fixes the author information")
            print("             on all the articles. May not be necessary anymore")
            print()
            print("Usage:")
            print("      -f (1-62)             Fixes the author info on all articles in given volume")
            print("      -f (1-62).(1-4)       Fixes the author info on all articles in given issue")
        elif arg == "-fr":
            print()
            print("Force Rename Command")
            print()
            print("Description: Force a title and author rename of a given article")
            print()
            print("Usage:")
            print("      -fr (1-62).(1-4).##   Where ## is the article number, allows user to rename the file manually") 
        elif arg == "-c":
            print()
            print("Confirm Command")
            print()
            print("Description: Displays the author and title on the PDF metadata")
            print()
            print("Usage:")
            print("      -c (1-62).(1-4).##    Where ## is the article number, displays the author on given article")
        elif arg == "-fo":
            print()
            print("Fix Out Command")
            print()
            print("Description: After confirming files are appropriate, use this to change file names")
            print()
            print("Usage:")
            print("      -fo")
        elif arg == "-ca":
            print()
            print("Author Folder Creator Command")
            print()
            print("Description: (UNFINISHED) Will go through and will sort authors based on name into author folder")
            print()
            print("Usage:")
            print("      -ca                   Moves all articles to correct author folder")
            print("      -ca (1-64)            Moves all articles in given volume to correct author folder")
            print("      -ca (1-64).(1-4)      Moves all articles in given issue to correct author folder")
            print("      -ca (1-64).(1-4).##   Moves given article to correct author folder")
        elif arg == "-o":
            print()
            print("Open File Command")
            print()
            print("Description: Opens the given article")
            print()
            print("Usage:")
            print("      -o (1-64).(1-4).##    Where ## is the article number, opens the article")
            
